=== What's new in 2.2 Since 2.1

==== Kafka Client Version

This version requires the 1.1.0 `kafka-clients` or higher.

==== Class/Package Changes

The class `ContainerProperties` has been moved from `org.springframework.kafka.listener.config` to `org.springframework.kafka.listener`.

The enum `AckMode` has been moved from `AbstractMessageListenerContainer` to `ContainerProperties`.

`setBatchErrorHandler()` and `setErrorHandler()` methods have been moved from `ContainerProperties` to `AbstractMessageListenerContainer` (and `AbstractKafkaListenerContainerFactory`).

==== After rollback processing

A new `AfterRollbackProcessor` strategy is provided - see <<after-rollback>> for more information.

==== ConcurrentKafkaListenerContainerFactory changes

The `ConcurrentKafkaListenerContainerFactory` can now be used to create/configure any `ConcurrentMessageListenerContainer`, not just those for `@KafkaListener` annotations.
See <<container-factory>> for more information.

==== Listener Container Changes

A new container property `missingTopicsFatal` has been added.

See <<kafka-container>> for more information.

Batch listeners can optionally receive the complete `ConsumerRecords<?, ?>` object instead of a `List<ConsumerRecord<?, ?>`.

See <<batch-listeners>> for more information.
